/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_Lua5_3 */
#ifndef _Included_io_vproxy_luajn_n_Lua5_3
#define _Included_io_vproxy_luajn_n_Lua5_3
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_3_isyieldable(LuaState * _L);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_Lua5_3
// metadata.generator-version: pni 21.0.0.8
// sha256:24d0fbe262a3dd9839dbdfe1330534328ea08f9f930c18c6b70358f7f5466c29
