/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaDebug */
#ifndef _Included_io_vproxy_luajn_n_LuaDebug
#define _Included_io_vproxy_luajn_n_LuaDebug
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT size_t JNICALL JavaCritical_io_vproxy_luajn_n_LuaDebug___getLayoutByteSize();

PNIEnvExpand(lua_Debug, lua_Debug *)
PNIBufExpand(lua_Debug, lua_Debug, JavaCritical_io_vproxy_luajn_n_LuaDebug___getLayoutByteSize())

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaDebug
// metadata.generator-version: pni 21.0.0.12
// sha256:cfe5187d45bc2a2afdd7d441dec8b5ae804881e37ee26d61e33c2148cdb56b32
