/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaOpenresty */
#ifndef _Included_io_vproxy_luajn_n_LuaOpenresty
#define _Included_io_vproxy_luajn_n_LuaOpenresty
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <luajit.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_LuaOpenresty_getExData(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaOpenresty_setExData(LuaState * _L, void * exdata);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_LuaOpenresty_getExData2(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaOpenresty_setExData2(LuaState * _L, void * exdata);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaOpenresty_resetThread(LuaState * _L, LuaState * _th);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaOpenresty
// metadata.generator-version: pni 21.0.0.8
// sha256:9fccf3e3ad955dd233132d6d62418a6424368fd8dceebe51a5a00b438e4310f1
