/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaDebug */
#ifndef _Included_io_vproxy_luajn_n_LuaDebug
#define _Included_io_vproxy_luajn_n_LuaDebug
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(lua_Debug, lua_Debug *)

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaDebug
// metadata.generator-version: pni 21.0.0.8
// sha256:a0ba0f49b23aa62e1358ddf3a4ca4ea13e73c3756d0f9e77524cb5debc82982e
