/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_Lua */
#ifndef _Included_io_vproxy_luajn_n_Lua
#define _Included_io_vproxy_luajn_n_Lua
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT LuaState * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_newState(LuaState * return_);
JNIEXPORT LuaState * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_newState2(void * allocF, void * ud, LuaState * return_);
JNIEXPORT LuaState * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_initState(void * _L, LuaState * return_);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_atPanic(LuaState * _L, void * func);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_dump(LuaState * _L, void * writer, void * data);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_load(LuaState * _L, void * reader, void * data, char * chunkName);
JNIEXPORT LuaState * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_newThread(LuaState * _L, LuaState * return_);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_loadFile(LuaState * _L, char * filename);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_loadString(LuaState * _L, char * s);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_gc(LuaState * _L, int32_t what, int32_t data);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_getAllocF(LuaState * _L, void * _ud);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua_getMetaTable(LuaState * _L, char * tname);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua_registerModule(LuaState * _L, char * libname);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_resume(LuaState * _L, int32_t narg);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua_setAllocF(LuaState * _L, void * allocF, void * ud);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_status(LuaState * _L);
JNIEXPORT char * JNICALL JavaCritical_io_vproxy_luajn_n_Lua_typename(LuaState * _L, int32_t tp);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_upValueIndex(int32_t index);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua_xmove(LuaState * _from, LuaState * _to, int32_t n);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua_version(LuaState * _L);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_Lua
// metadata.generator-version: pni 21.0.0.8
// sha256:a7089128207643ceed95f11359916be8220ca3df03c85c40042aebbf9f292b51
