/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_HelperLuaJIT */
#ifndef _Included_io_vproxy_luajn_n_HelperLuaJIT
#define _Included_io_vproxy_luajn_n_HelperLuaJIT
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <luajit.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_MASK(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_ENGINE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_DEBUG(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_FUNC(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_ALLFUNC(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_ALLSUBFUNC(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_TRACE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_WRAPCFUNC(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_MAX(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_OFF(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_ON(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_HelperLuaJIT_LUAJIT_MODE_FLUSH(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_HelperLuaJIT
// metadata.generator-version: pni 21.0.0.8
// sha256:99bcddb4e9a8d36c31b199ebd4cc15075360929bbb54c8b309059e3d4ce1140c
