/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_Lua5_2 */
#ifndef _Included_io_vproxy_luajn_n_Lua5_2
#define _Included_io_vproxy_luajn_n_Lua5_2
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_2_copy(LuaState * _L, int32_t fromidx, int32_t toidx);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_2_upValueId(LuaState * _L, int32_t funcindex, int32_t n);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_2_upValueJoin(LuaState * _L, int32_t funcindex1, int32_t n1, int32_t funcindex2, int32_t n2);
JNIEXPORT double JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_2_toNumberX(LuaState * _L, int32_t index, int32_t * isnum);
JNIEXPORT int64_t JNICALL JavaCritical_io_vproxy_luajn_n_Lua5_2_toIntegerX(LuaState * _L, int32_t index, int32_t * isnum);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_Lua5_2
// metadata.generator-version: pni 21.0.0.8
// sha256:3023697637f27cb90c160e117eb9f6c106ef035eb9b198335b7907609465e8b1
