/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaLibLuaJIT */
#ifndef _Included_io_vproxy_luajn_n_LuaLibLuaJIT
#define _Included_io_vproxy_luajn_n_LuaLibLuaJIT
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLibLuaJIT_openBit(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLibLuaJIT_openJIT(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLibLuaJIT_openFFI(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLibLuaJIT_openStringBuffer(LuaState * _L);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaLibLuaJIT
// metadata.generator-version: pni 21.0.0.8
// sha256:0ff80551c6c45a13f2fd2e0d74c36a203364ec658ed4009c659f6939f68e7c87
