/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_Helper5_2 */
#ifndef _Included_io_vproxy_luajn_n_Helper5_2
#define _Included_io_vproxy_luajn_n_Helper5_2
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper5_2_LUA_GCISRUNNING(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper5_2_LUA_OK(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper5_2_LUA_RIDX_GLOBALS(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_Helper5_2
// metadata.generator-version: pni 21.0.0.8
// sha256:b8c17dfa39f0b1b90640525d0ac6df153f644d78f39381615e35f6d37c1174b7
