/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaJIT */
#ifndef _Included_io_vproxy_luajn_n_LuaJIT
#define _Included_io_vproxy_luajn_n_LuaJIT
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <luajit.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_LuaJIT_setMode(LuaState * _L, int32_t idx, int32_t mode);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaJIT
// metadata.generator-version: pni 21.0.0.8
// sha256:6522bb0c0bcf7574c1b5beaad7223c21415948a6a616d74716715693571f5548
