/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_Helper */
#ifndef _Included_io_vproxy_luajn_n_Helper
#define _Included_io_vproxy_luajn_n_Helper
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Helper_flushStdout(void);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_Helper_memset(void * b, int32_t c, int64_t len);
JNIEXPORT void * JNICALL JavaCritical_io_vproxy_luajn_n_Helper_temporaryVariablesTableIndex(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_REGISTRYINDEX(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_ENVIRONINDEX(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GLOBALSINDEX(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_YIELD(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_ERRRUN(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_ERRSYNTAX(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_ERRMEM(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_ERRERR(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MULTRET(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TNONE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TNIL(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TBOOLEAN(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TLIGHTUSERDATA(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TNUMBER(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TSTRING(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TTABLE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TFUNCTION(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TUSERDATA(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_TTHREAD(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MINSTACK(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCSTOP(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCRESTART(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCCOLLECT(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCCOUNT(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCCOUNTB(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCSTEP(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCSETPAUSE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_GCSETSTEPMUL(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_HOOKCALL(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_HOOKRET(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_HOOKLINE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_HOOKCOUNT(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_HOOKTAILRET(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MASKCALL(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MASKRET(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MASKLINE(void);
JNIEXPORT int32_t JNICALL JavaCritical_io_vproxy_luajn_n_Helper_LUA_MASKCOUNT(void);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_Helper
// metadata.generator-version: pni 21.0.0.8
// sha256:c9598327ba6cbe62281a21a550e791fc80212a1e405f6d5005509706ed4ee534
