/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_n_LuaLib */
#ifndef _Included_io_vproxy_luajn_n_LuaLib
#define _Included_io_vproxy_luajn_n_LuaLib
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include "io_vproxy_luajn_n_LuaState.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openLibs(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openLuaJN(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openBase(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openMath(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openString(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openTable(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openIO(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openOS(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openPackage(LuaState * _L);
JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_n_LuaLib_openDebug(LuaState * _L);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_n_LuaLib
// metadata.generator-version: pni 21.0.0.8
// sha256:6a3cb39d1f8453e67ea5c292deca52d35985dfe625ccc9961b5e742139b4581c
