/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_tutorial_TutorialNative */
#ifndef _Included_io_vproxy_luajn_tutorial_TutorialNative
#define _Included_io_vproxy_luajn_tutorial_TutorialNative
#ifdef __cplusplus
extern "C" {
#endif

struct TutorialNative;
typedef struct TutorialNative TutorialNative;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(TutorialNative, TutorialNative *)

PNI_PACK(struct, TutorialNative, {
    int32_t intValue; /* padding */ uint64_t :32;
    int64_t longValue;
});

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_tutorial_TutorialNative_dummyPlaceHolderForGeneratingImplHFile(TutorialNative * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_tutorial_TutorialNative
// metadata.generator-version: pni 21.0.0.8
// sha256:2ecffc2e9ade632c2b9983b3466373eb2d8da937c648f775164378b52b54b596
