/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_tutorial_TutorialUpcall */
#ifndef _Included_io_vproxy_luajn_tutorial_TutorialUpcall
#define _Included_io_vproxy_luajn_tutorial_TutorialUpcall
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL luajn_tutorial_ls_add(PNIRef * ls, char * str);
JNIEXPORT void JNICALL luajn_tutorial_ls_remove(PNIRef * ls, int32_t index);
JNIEXPORT int32_t JNICALL luajn_tutorial_ls_size(PNIRef * ls);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_tutorial_TutorialUpcall
// metadata.generator-version: pni 21.0.0.8
// sha256:d0661dd545cc4f85ba3b8bf10b44fe090e4a46f84ad58186691432a4b67c7538
