/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class io_vproxy_luajn_tutorial_TutorialNative */
#ifndef _Included_io_vproxy_luajn_tutorial_TutorialNative
#define _Included_io_vproxy_luajn_tutorial_TutorialNative
#ifdef __cplusplus
extern "C" {
#endif

struct TutorialNative;
typedef struct TutorialNative TutorialNative;

#ifdef __cplusplus
}
#endif

#include <jni.h>
#include <pni.h>
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

#ifdef __cplusplus
extern "C" {
#endif

PNIEnvExpand(TutorialNative, TutorialNative *)
PNIBufExpand(TutorialNative, TutorialNative, 16)

struct TutorialNative {
    int32_t intValue;
    int64_t longValue;
};

JNIEXPORT void JNICALL JavaCritical_io_vproxy_luajn_tutorial_TutorialNative_dummyPlaceHolderForGeneratingImplHFile(TutorialNative * self);

#ifdef __cplusplus
}
#endif
#endif // _Included_io_vproxy_luajn_tutorial_TutorialNative
// metadata.generator-version: pni 21.0.0.13
// sha256:c7e09ed03658a691d0faf7366e3d0db35f591acd4177e71d7ab39e496744c998
